easy_admin:
    site_name: 'Provoke'
    design:
        menu:
            - label: 'Provoke'
            - label: 'Produits'
              icon: 'database'
              children:
                - {entity: 'MainCategorie', icon: 'inbox', label: 'Categories Principales'}
                - {entity: 'Categorie', icon: 'inbox', label: 'Sous-Categories'}
                - {entity: 'Article', icon: 'inbox', label: 'Articles'}
            - label: 'Clients'
            - label: 'Clients'
              icon: 'database'
              children:
                - {entity: 'Client', icon: 'inbox', label: 'Clients'}
            - label: 'Commandes'
    entities:
        MainCategorie:
            class: App\Entity\MainCategorie
            form:
              fields:
                - {property: 'nom'}
                - {property: 'url'}
        Categorie:
            class: App\Entity\Categorie
            list:
                fields:
                    - "nom"
                    - { property: 'image', type: 'image', base_path: '%app.path.categorie_images%' }
                    - "mainCategorie"
            form:
                fields:
                    - "nom"
                    - { property: 'imageFile', type: 'vich_image' }
                    - "mainCategorie"
                    - "articles"
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.categorie_images%' }  
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - "nom"
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - "prix"
                    - "actif"
                    - "categorie"
                    - "caracteristiques" 
            form:
                fields:
                    - "nom"
                    - "url"
                    - "description"
                    - "prix"                
                    - { property: 'imageFile', type: 'vich_image' }
                    - "actif"
                    - "categorie"
                    - "caracteristiques"    
                actions:
                    - {name: 'editer', icon: 'pencil', label: false, css_class: 'btn btn-secondary'} 
                    - {name: 'supprimer', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }            
        Client:
            class: App\Entity\Client
            list:
                fields:
                    - "nom"
                    - "prenom"
                    - "email"
                    - "adresse"
                    - "codePostal"
                    - "ville"
                    - "pays"