<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH9GxoeR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH9GxoeR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH9GxoeR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH9GxoeR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH9GxoeR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H9GxoeR',
    'container.build_id' => 'a962efd8',
    'container.build_time' => 1554297067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH9GxoeR');
