<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIO8MbPY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIO8MbPY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIO8MbPY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIO8MbPY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIO8MbPY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IO8MbPY',
    'container.build_id' => '5b10aa39',
    'container.build_time' => 1551646209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIO8MbPY');
